name: issues
on: issues
jobs:
    information:
        runs-on: ubuntu-latest
        steps:
          - name: output event details
            run : |
                echo  "the event is ${{ toJson(github.event) }}"